### ISSUE TITLE
Set up Travis CI

### ISSUE THREAD

**Issue by kubawerlos** [slk500/fighterchamp#14]
Travis CI for open source project is extremely easy to set up. `.travis.yml` with content like:
```
language: php

php:
    - 7.3

install:
    - make docker-build
    - make composer-install

script:
    - make test
```

Should be enough for start.

**Comment by slk500** [comment]
It's great idea, but I could't make it work. Maybe someone else can configure it.

**Comment by kubawerlos** [comment]
Done in https://github.com/slk500/fighterchamp/pull/18
